version: '3.8'

services:

  react-portfolio:
    container_name: react-portfolio
    restart: always
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: react-portfolio:latest
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true